version: "3.3"
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "emanuel"
      # You can use whatever password you like
      MYSQL_PASSWORD: "emanuel"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - /home/emanuel/public_html/web-server/Databases/mysql:/var/lib/mysql
      # - /home/emanuel/Databases/mysql:/var/lib/mysql
      # - $PWD/mysql.conf:/etc/mysql/conf.d/mysql.cnf
  postgress-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      # <Port exposed> : < Postgres Port running inside container>
      - "5432:5432"
    expose:
      # Opens port 5432 on the container
      - "5432"
      # Where our data will be persisted
    volumes:
      - /home/emanuel/public_html/web-server/Databases/postgres:/var/lib/postgresql/data
  redis-db:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/emanuel/public_html/web-server/Databases/mongo:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 6500:6500
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    environment:
      - ADMINER_DESIGN='nette'
  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9002:80
    environment:
      - "PGADMIN_DEFAULT_EMAIL=emanueldina@refactory.id"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    links:
      - "postgress-db:pgsql-server"